from basemodels import FunctionDefinition, ParameterSpec
from enum import Enum
import re


class ParamType(Enum):
    NUMBER = "number"
    STRING = "string"
    BOOL = "boolean"
    INTEGER = "integer"
    FLOAT = "float"


class CandidateStatus(Enum):
    VALID_COMPLETE = "valid_complete"
    VALID_PREFIX = "valid_prefix"
    INVALID = "invalid"


def check_candidate_logits(
        candidate: str, allowed: list[str]
        ) -> CandidateStatus:
    """
    Check if context generated by the model is matching correctly
     the expected output"""
    for function_name in allowed:
        if candidate == function_name:
            return CandidateStatus.VALID_COMPLETE
        elif function_name.startswith(candidate):
            return CandidateStatus.VALID_PREFIX
    return CandidateStatus.INVALID


def is_valid_number(value: str) -> bool:
    """Check if a candidate is valid number"""
    try:
        float(value)
        return True
    except ValueError:
        return False


def is_bool(value: str) -> bool:
    """Check if a candidate is a valid boolean"""
    if value in 'False' or value in 'True':
        return True
    return False


def find_stop_char(token_text: str) -> str | None:
    """Busca el primer carácter de corte dentro del token, si existe"""
    for i, char in enumerate(token_text):
        if (
            char == 'Ċ' or
            char == '"' or
            ord(char) < 0x20
                ):
            return token_text[:i]  # lo que hay antes del carácter de corte
    return None  # no hay carácter de corte, todo el token es válido


def build_context_for_fn_name(
        functions: list[FunctionDefinition], prompt: str
        ) -> str:
    """Built a context text for finding correct function name"""
    functions_text = "\n".join(
            f"- {f.name}: {f.description}" for f in functions)
    context: str = (
        f"check function definition {functions_text} and"
        f"return a function name that solve this request: {prompt}."
        "Answer: "
        )
    return context


# def build_context_for_parameter(
#         prompt: str, function: FunctionDefinition
#         ) -> str:
#     fn_name: str = function.name
#     fn_description: str = function.description
#     # fn_return: str = function.returns
#     context: str = (
#         f"Given this request: '{prompt}', "
#         f"to be solved with the function '{fn_name}' "
#         f"with the description: '{fn_description}', "
#         f"find the parameters needed in '{fn_name}' to solve request.\n"
#         "Preserve the original spelling, capitalization, punctuation, "
#         "and formatting of parameter values from the user request unless "
#         "a transformation is explicitly requested.\n"
#         f"'parameters:' "
#     )
#     return context


def build_context_for_parameter(
        prompt: str, function: FunctionDefinition
        ) -> str:
    fn_name: str = function.name
    fn_description: str = function.description
    context: str = (
        'Selected function:\n'
        f'{fn_name}\n'
        f'Description:\n'
        f'{fn_description}\n'
        f'Parameters:\n'
    )
    for p_name, p_definition in function.parameters.items():
        context += f"- {p_name}: {p_definition.type}\n"
    context += (
        f'Request "{prompt}"\n'
        'Return a function call in JSON format with keys "name"'
        'and "parameters".\n'
        'Preserve the original spelling, capitalization, punctuation, '
        'and formatting of parameter values from the user request unless '
        'a transformation is explicitly requested.\n'
        f'\n{{"name": "{fn_name}", "parameters": {{'
    )
    return context


def preserve_literal_string_value(
    value: str,
    user_prompt: str
) -> str:
    """
    Preserve the exact text formatting of a generated string value.

    The function searches the original user prompt for a unique
    case-insensitive match of the generated value. If exactly one match
    is found, the original spelling and capitalization from the prompt
    are returned. Otherwise, the generated value is left unchanged.

    Args:
        value: String value generated by the model.
        user_prompt: Original natural-language request from the user.

    Returns:
        The matching text from the original prompt when a unique match
        exists, otherwise the original generated value.
    """
    if not value:
        return value
    pattern = re.escape(value)
    if value[0].isalnum():
        pattern = r"\b" + pattern
    if value[-1].isalnum():
        pattern = pattern + r"\b"
    matches = list(
        re.finditer(
            pattern,
            user_prompt,
            flags=re.IGNORECASE
        )
    )
    if len(matches) == 1:
        return matches[0].group(0)
    return value


def clean_param_value(text: str) -> str:
    """Clean spaces and ' from the string"""
    clean_spaces = text.strip()  
    return re.sub(r'\\+', r'\\', clean_spaces)


def clean_number(text: str) -> str:
    """Clean .000 from numbers"""
    clean: str = text.rstrip('0').rstrip('.')
    return clean
