from basemodels import FunctionDefinition
from enum import Enum


class ParamType(Enum):
    NUMBER = "number"
    STRING = "string"
    BOOL = "boolean"
    INTEGER = "integer"
    FLOAT = "float"


class CandidateStatus(Enum):
    VALID_COMPLETE = "valid_complete"
    VALID_PREFIX = "valid_prefix"
    INVALID = "invalid"


def check_candidate_logits(
        candidate: str, allowed: list[str]
        ) -> CandidateStatus:
    """
    Check if context generated by the model is matching correctly
     the expected output"""
    for function_name in allowed:
        if candidate == function_name:
            return CandidateStatus.VALID_COMPLETE
        elif function_name.startswith(candidate):
            return CandidateStatus.VALID_PREFIX
    return CandidateStatus.INVALID


def is_valid_number(value: str) -> bool:
    """Check if a candidate is valid number"""
    try:
        float(value)
        return True
    except ValueError:
        return False


def is_bool(value: str) -> bool:
    """Check if a candidate is a valid boolean"""
    if value in 'False' or value in 'True':
        return True
    return False


def find_stop_char(token_text: str) -> str | None:
    """Busca el primer carácter de corte dentro del token, si existe"""
    for i, char in enumerate(token_text):
        if ord(char) < 0x20: # or char == "\\" or char == 'Ċ'
            return token_text[:i]  # lo que hay antes del carácter de corte
    return None  # no hay carácter de corte, todo el token es válido


def build_context_for_fn_name(
        functions: list[FunctionDefinition], prompt: str
        ) -> str:
    """Built a context text for finding correct function name"""
    functions_text = "\n".join(
            f"- {f.name}: {f.description}" for f in functions)
    context: str = (
        f"check function definition {functions_text} and"
        f"return a function name that solve this request: {prompt}."
        "Answer: "
        )
    return context


def build_context_for_parameter(
        prompt: str, function: FunctionDefinition
        ) -> str:
    fn_name: str = function.name
    fn_description: str = function.description
    # fn_return: str = function.returns
    context: str = (
        f"Given this request: '{prompt}', "
        f"to be solved with the function {fn_name} "
        f"that {fn_description} "
        f"find the parameters needed in {fn_name}:"
        "Preserve the original spelling, capitalization, punctuation, "
        "and formatting of parameter values from the user request unless "
        "a transformation is explicitly requested.\n"
    )
    return context


def clean_param_value(text: str) -> str:
    """Clean spaces and ' from the string"""
    clean_spaces = text.strip()
    clean_q_marks = clean_spaces.strip("'")
    clean_double_q_marks = clean_q_marks.strip('"')
    return clean_double_q_marks.strip("'")


def clean_number(text: str) -> str:
    """Clean .000 from numbers"""
    clean_zero: str = text.rstrip('0').rstrip('.')
    return clean_zero

