from llm_sdk import Small_LLM_Model
from basemodels import ParameterSpec, FunctionDefinition, PromptItem
from enum import Enum
import json
from typing import Any


class DecodingError(Exception):
    """Custom error for decoding"""
    pass


class CandidateStatus(Enum):
    VALID_COMPLETE = "valid_complete"
    VALID_PREFIX = "valid_prefix"
    INVALID = "invalid"


def check_candidate_logits(
        candidate: str, allowed: list[str]
        ) -> CandidateStatus:
    """
    Check if context generated by the model is matching correctly
     the expected output"""
    for function_name in allowed:
        if candidate == function_name:
            return CandidateStatus.VALID_COMPLETE
        elif function_name.startswith(candidate):
            return CandidateStatus.VALID_PREFIX
    return CandidateStatus.INVALID


def decode_fn_name(
        model: Small_LLM_Model,
        vocab: dict[int, str],
        context: str,
        allowed: list[str]) -> str:
    """Find the next token to form the fn_name"""
    encoded = model.encode(context)
    input_ids = encoded[0].tolist()
    candidate: str = ""
    fn_name: str = ""
    status = check_candidate_logits(candidate, allowed)
    # invalid tokens to logit -inf
    while status != CandidateStatus.VALID_COMPLETE:
        logits = model.get_logits_from_input_ids(input_ids)
        for token_id in range(len(logits)):
            token_text = vocab.get(token_id)
            if token_text is None:
                logits[token_id] = float("-inf")
                continue
            candidate = fn_name + token_text   # <- se recalcula desde fn_name cada vez, no +=
            status = check_candidate_logits(candidate, allowed)
            if status == CandidateStatus.INVALID:
                logits[token_id] = float("-inf")

        if max(logits) == float("-inf"):
            raise DecodingError("No matches found for function name")
        next_token_id = logits.index(max(logits))
        input_ids.append(next_token_id)
        decoded_next_token = vocab[next_token_id]
        context += decoded_next_token
        fn_name += decoded_next_token
        status = check_candidate_logits(fn_name, allowed)  # <- recalcular status con fn_name real

    return fn_name



def decode_parameters(
        model: Small_LLM_Model,
        vocab: dict[int, str],
        prompt: str,
        function: FunctionDefinition,
        context: str) -> dict[str, str]:
    """decode parameters needed to run function"""
    funct_param: dict[str, ParameterSpec] = function.parameters
    param_names: list[str] = [name for name in funct_param.keys()]
    prompt_list: list[str] = prompt.split()
    param_return: dict[str, str] = {}
    print(param_names)
    for param in param_names:
        context += f"param '{param}' value:"
        encoded = model.encode(context)
        input_ids = encoded[0].tolist()
        candidate: str = ""
        param_value: str = ""
        logits = model.get_logits_from_input_ids(input_ids)
        status = check_candidate_logits(candidate, prompt_list)
        while status != CandidateStatus.VALID_COMPLETE:
            for token_id in range(len(logits)):
                token_text = vocab.get(token_id)
                if token_text is None:
                    logits[token_id] = float("-inf")
                    continue
                candidate = param_value + token_text
                status = check_candidate_logits(candidate, prompt_list)
                if status == CandidateStatus.INVALID:
                    logits[token_id] = float("-inf")
                else:
                    print(f"context: {context}")
                    print(f"candidato: {candidate}")

            if max(logits) == float("-inf"):
                raise DecodingError("No matches found for parameter value")
            next_token_id = logits.index(max(logits))
            input_ids.append(next_token_id)
            decoded_next_token = vocab[next_token_id]
            context += decoded_next_token
            param_value += decoded_next_token
            status = check_candidate_logits(param_value, prompt_list)
            if status == CandidateStatus.VALID_COMPLETE:
                param_return[param] = param_value
    return param_return  


def decode(prompt: str, functions: list[FunctionDefinition]) -> dict[str, Any]:
    """Start the decode process"""
    model = Small_LLM_Model()
    vocab_path: str = model.get_path_to_vocab_file()
    object_return: dict[str: Any] = {}
    print(f"Prompt to resolve: {prompt}")
    try:
        with open(vocab_path) as f:
            vocab_file = json.load(f)
            vocab: dict[int, str] = {v: k for k, v in vocab_file.items()}
    except (
        FileNotFoundError, PermissionError
    ):
        raise DecodingError("Model vocab file couldn't be found")
    allowed_fn_names: list[str] = []
    for function in functions:
        allowed_fn_names.append(function.name)
    print(f"nombres de funcion: {allowed_fn_names}")
    if len(allowed_fn_names) == 0:
        raise DecodingError(
            "No function names found in the function definitions input file"
            )
    fn_initial_context: str = (
        f"Given the user prompt: {prompt}, "
        "choose correct function name. Answer: "
    )
    fn_name: str = decode_fn_name(
        model, vocab, fn_initial_context, allowed_fn_names
        )
    function: FunctionDefinition = next(
        function for function in functions
        if function.name == fn_name
    )
    param_initial_context: str = (
        f"Given the user prompt: {prompt} and the function {function} "
        "find the correct parameters:"
    )
    parameters: dict[str, str] = decode_parameters(
        model, vocab, prompt, function, param_initial_context
        )
    print(parameters)
    object_return = {
        'prompt': prompt,
        'name': fn_name,
        'parameters': parameters
    }
    return object_return
